---
AllCops:
  Exclude:
  - vendor/**/*
Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 29
Metrics/BlockLength:
  Max: 29
AllCops:
  TargetRubyVersion: 2.2
