name: New release

on:
  push:
    branches:
      - master

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: create release draft
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          future_release: ${{ steps.version.outputs.next-version }}

      - name: Generate changelog for the release
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          since_tag: ${{ steps.previoustag.outputs.tag }}
          future_release: ${{ steps.version.outputs.next-version }}
          output: CHANGELOGRELEASE.md

      - name: update inspec.yml
        uses: mikefarah/yq@3.2.1
        with:
          cmd: yq w -I4 -i inspec.yml version ${{ steps.version.outputs.next-version }} && sed -i '1i---' inspec.yml

      - name: push inspec.yml and changelog
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update inspec.yml and changelog'
          files: inspec.yml CHANGELOG.md
          name: dev-sec CI
          email: hello@dev-sec.io
          rebase: 'true'

      - name: Read CHANGELOG.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOGRELEASE.md

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Get current commitish
        id: current_commitish
        run: echo "::set-output name=sha::$(git log -1 --format="%H")"

      - name: Check it
        run: echo ${{ steps.current_commitish.outputs.sha }}

      - name: Create Release draft
        id: create_release
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: ${{ steps.version.outputs.next-version }}
          tag_name: ${{ steps.version.outputs.next-version }}
          body: |
            ${{ steps.package.outputs.content }}
          commitish: ${{ steps.current_commitish.outputs.sha }}
          draft: true
