name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    uses: dev-sec/.github/.github/workflows/baseline-test.yml@main
